name: Build and Publish Wheels

on:
  push:
    tags:
      - 'v*.*.*'  # Build on version tags

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Build on Linux, macOS, and Windows
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12]  # Target different Python versions

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install cibuildwheel==2.x.x  # Install cibuildwheel (you can pin to a specific version)

      - name: Build wheels
        run: cibuildwheel --output-dir dist  # CIBuildWheel builds the wheels and places them in `dist/`

      - name: Upload wheels to PyPI
        if: startsWith(github.ref, 'refs/tags')  # Only upload if it's a tagged release
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ __token__ }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
